### ISSUE TITLE
Notes for help/tutorial pages

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/project-iiif-annotate#32] opened 2017-07-28 11:19 UTC
Such as https://github.com/LibCrowds/project-iiif-annotate/blob/master/config/help.json

Provide guidance to draw as closely as possible around a title while still including the tails etc of letters and any subtitles.

Include images like the below as an example of information about future performances that shouldn't be included.

![for playbills tutorial 2017-07-28t10-17-23 298z](https://user-images.githubusercontent.com/380763/28715243-e92069ba-738e-11e7-903b-eab68ca236fb.png)

**Comment by alexandermendes** [comment] 2017-09-19 10:52
Duplicate of https://github.com/LibCrowds/project-playbills/issues/11

**Closed as completed by alexandermendes** 2017-09-19 10:53 UTC
